server:
  port: 9000

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

#          search-locations: file:///home/ngochung1809/Desktop/microservice-payment/config-server/src/main/resources/config

#        git:
#          uri: https://github.com/microservice-app-payment/spring-app-config.git
#          clone-on-start: on
#          default-label: master


encrypt:
  key: eazybytes

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8000/eureka}
