server:
  port: 9296
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/microservice-app-payment/spring-app-config.git
          clone-on-start: on

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: on
#    fetch-registry: on
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
